#pragma once

#include "../src/guid.h"
#include "../src/node-base/node.h"
#include "../src/document.h"
#include "../src/page.h"
#include "../src/frame.h"
#include "../src/rectangle.h"
#include "../src/ellipse.h"
#include "../src/line.h"
#include "../src/polygon.h"
#include "../src/star.h"
#include "../src/text.h"
#include "../src/symbol.h"
#include "../src/instance.h"
#include "../src/vector.h"
#include "../src/container.h"
